server:
  port: 8085
spring:
  application:
    name: service-inventory
  datasource:
    url: jdbc:postgresql://localhost:5436/duongtech_inventory
    username: postgres
    password: 10112004
  # Tự động nạp dữ liệu mẫu từ classpath:data.sql (chạy sau khi Hibernate tạo bảng)
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
