server:
  port: 8084
spring:
  application:
    name: service-payment
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-payment:5432/food_ordering_payment}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:10112004}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
# SePay / VietQR Configuration
sepay:
  bank-account-number: ${SEPAY_BANK_ACCOUNT_NUMBER:}
  bank-code: ${SEPAY_BANK_CODE:MB}
  account-name: ${SEPAY_ACCOUNT_NAME:NGUYEN VAN A}
  api-token: ${SEPAY_API_TOKEN:}
  api-url: ${SEPAY_API_URL:https://my.sepay.vn/userapi}
  frontend-url: ${SEPAY_FRONTEND_URL:http://localhost:3000}

logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [%level] [PAYMENT-SERVICE] %msg%n"



